# Site settings

source: src
title: سیمرغ # site title
description: >- # site description
  یک تم فارسی برای Jekyll.  کد سیمرغ در <a href="https://github.com/mhdzli/simorq" target="_blank" rel="noopener">گیت‌هاب</a>.
lang: fa # default lang
timezone: Asia/Tehran # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/mhdzli/simorgh # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: اسم شما # author name
  bio: >- # tell to the world
    یک تم Jekyll برای وبلاگ فارسی. اگر تم روشن را بیشتر می‌پسندید، روی خورشید بالای صفحه سمت راست کلیک کنید.

    لینک این پروژه در
    <a href="https://github.com/mhdzli/simorq" target="_blank" rel="noopener">گیت‌هاب</a>.

  username:  your_username # general username
  github: your_github_username # github username
  twitter: your_twitter_username # twitter username
  # you can add your accounts of other social media  but you need to edit footer.html in _includes directory and add other sosial media links based on existing  templates
  
  lbry: https://your_instance.address/@your_username # lbry url
  pixelfed: https://your_instance.address/your_username # your pixelfed url
  mastodon: # mastodon urls
    first: https://your_instance.address/@your_username
    second: 
  email: your@email.address # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://example.anything" # your domain 
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-jalali
